title: OviBlog
author: toppiovi
email: tobias.oefner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On my OviBlog I intend to share my experiences and learnings as a software developer. 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: OefnerTobias # DO NOT include the @ character, or else the build will fail!
github_username:  toppiovi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
